*** %LET NEWMONTHFILE = NOVEMBERAPPS                               ***;
*** %LET APPIMPORTFILE = APPIMPORTFILE2                            ***;
*** %LET RECENTMONTHNO = 11                                        ***;
*** %LET ONEMOAGO = 10                                             ***;
*** %LET TWOMOAGO = 9                                              ***;
*** %LET TWOMOBOOKED= SEPTEMBERAPPSB                               ***;
*** %LET TWOMOUNBOOKED = SEPTEMBERAPPSUNB                          ***;
*** %LET APPSMINUES2MOAGO = APPSEXCEPTSEPTEMBER                    ***;
*** %LET ALLAPPSFILE = ALLAPPS_OCTOBERFINAL                        ***;
*** %LET ONEMOBOOKED = OCTOBERAPPSB                                ***;
*** %LET ONEMOUNBOOKED = OCTOBERAPPSUNB                            ***;
*** %LET APPSMINUES1MOAGO = APPSEXCEPTOCTOBER                      ***;
*** %LET ALLAPPSFILE2 = ALLAPPS_OCTOBERFINAL                       ***;
***                                                                ***;
*** %LET ALLAPPS_HIST_LOC =                                        ***;
*** "\\mktg-app01\E\Vishwa\webreport\Production\Web\AllApps_History_2.xlsx"***;

PROC IMPORT 
	DATAFILE = &AllApps_Hist_loc. DBMS = EXCEL OUT = APPIMPORTFILE 
		REPLACE;
RUN;

*** CHECKS ------------------------------------------------------- ***;
PROC SQL;
	SELECT MIN(ENTDATE) AS MIN_ENTDATE,
		   MAX(ENTDATE) AS MAX_ENTDATE,
		   MIN(APPDATE) AS MIN_APPDATE FORMAT date9.,
		   MAX(APPDATE) AS MAX_APPDATE FORMAT date9.,
		   MIN(NETLOANAMOUNT) AS MIN_NETLOANAMOUNT,
		   MAX(NETLOANAMOUNT) AS MAX_NETLOANAMOUNT,
		   MIN(NETLOANAMT_201802) AS MIN_NETLOANAMOUNT_201802,
		   MAX(NETLOANAMT_201802) AS MAX_NETLOANAMOUNT_201802
	FROM APPIMPORTFILE 
 /* WHERE NETLOANAMOUNT > 0 */;
QUIT;

*** DATA APPIMPORTFILE(DROP = APPDATE_SAS AMTREQUESTED DWOWNBR     ***;
***				       RENAME =(APPDATE_SAS1 = APPDATE_SAS         ***;
***							    AMTREQUESTED_NUM = AMTREQUESTED    ***;
***							    DWOWNBR_NUM = DWOWNBR));           ***;
*** 	SET APPIMPORTFILE;                                         ***;
*** 	APPDATE_SAS1 = APPDATE * 1;                                ***;
*** 	FORMAT APPDATE_SAS1 date9.;                                ***;
*** 	AMTREQUESTED_NUM = INPUT(AMTREQUESTED, 10.);               ***;
***  /* APPMONTH_NUM = INPUT(APPMONTH, 8.); */                     ***;
*** 	DWOWNBR_NUM = PUT(DWOWNBR, $8.);                           ***;
*** RUN;                                                           ***;
*** -------------------------------------------------------------- ***;

DATA APPIMPORTFILE2;
	SET APPIMPORTFILE;
	LENGTH APPNUMBER $10 PORTALAPPID $10 LTFILTER_ROUTINGID $10
		   WORKPHONE $12 CELLPHONE $12 FIRSTNAME $50 MIDDLENAME $50
		   LASTNAME $50 EMAIL $100 FULLADDRESS $120 ADR1 $80 ADR2 $25
		   CITY $50 LOANTYPE $25;
	CLASSID2 = CLASSID * 1;
	APRATE2 = APRATE * 1;
	EFFRATE2 = EFFRATE * 1;
	ORGTERM2 = ORGTERM * 1;
	CRSCORE2 = CRSCORE * 1;
	NETLOANAMOUNT2 = NETLOANAMOUNT * 1;
	ENTRYMONTH2 = ENTRYMONTH * 1;
	ENTDATE_SAS2 = INPUT(STRIP(TRIM(ENTDATE)), yymmdd10.);
	APPDATEMINUSENTDATE2 = (APPDATE - INPUT(STRIP(TRIM(ENTDATE)),
											yymmdd10.)) * 1;
	ENTDATEMINUSAPPDATE2 = (INPUT(STRIP(TRIM(ENTDATE)), 
								  yymmdd10.) - APPDATE) * 1;
	APPFICO2 = SUBSTR(STRIP(TRIM(APPFICO)), 1, 3) * 1;
	BOOKED_MONTH2 = MONTH(INPUT(ENTDATE, yymmdd10.));
	TOTALLOANCOST2 = INPUT(TOTALLOANCOST, 5.);
	DROP TOTALLOANCOST BOOKED_MONTH APPFICO CLASSID APRATE EFFRATE
		 ORGTERM CRSCORE NETLOANAMOUNT ENTDATE_SAS APPDATEMINUSENTDATE
		 ENTDATEMINUSAPPDATE ENTYRMONTH;
	RENAME TOTALLOANCOST2 = TOTALLOANCOST 
		   BOOKED_MONTH2 = BOOKED_MONTH 
		   APPFICO2 = APPFICO 
		   CLASSID2 = CLASSID 
		   APRATE2 = APRATE 
		   EFFRATE2 = EFFRATE 
		   ORGTERM2 = ORGTERM 
		   CRSCORE2 = CRSCORE 
		   NETLOANAMOUNT2 = NETLOANAMOUNT 
		   ENTDATE_SAS2 = ENTDATE_SAS 
		   APPDATEMINUSENTDATE2 = APPDATEMINUSENTDATE
		   ENTDATEMINUSAPPDATE2 = ENTDATEMINUSAPPDATE
		   ENTYRMONTH2 = ENTYRMONTH;
RUN;

DATA APPIMPORTFILE2;
	LENGTH APPNUMBER $10 PORTALAPPID $10 LTFILTER_ROUTINGID $10
		   WORKPHONE $12 CELLPHONE $12 FIRSTNAME $50 MIDDLENAME $50
		   LASTNAME $50 EMAIL $100 FULLADDRESS $120 ADR1 $80 ADR2 $25
		   CITY $50 LOANTYPE $25;
	SET APPIMPORTFILE2 &newmonthfile;
RUN;

***CHECKS -------------------------------------------------------- ***;
PROC SQL;
	SELECT ENTYRMONTH, SUM(BOOKED) FROM APPIMPORTFILE2 GROUP BY 1;
	SELECT APPYRMONTH, COUNT(APPNUMBER) FROM APPIMPORTFILE2 GROUP BY 1;
QUIT;

DATA APPIMPORTFILE2;
	SET APPIMPORTFILE2;
	FORMAT ENTDATE_SAS date9.;
RUN;

DATA MERGEDXX;
	SET &appimportfile;
	IF APPYRMONTH NE &recentmonthNO;
RUN;

DATA &twomobooked &twomoUNbooked;
	SET MERGEDXX; /* LAST ITERATION OF FINAL FILE */
	IF APPYRMONTH = &twomoago;
	IF BOOKED = 1 THEN OUTPUT &twomobooked;
	ELSE OUTPUT &twomoUNbooked;
RUN;

PROC SORT 
	DATA = VW_L; 
	BY SSNO1; 
RUN;

PROC SORT 
	DATA = &twomoUNbooked; 
	BY SSNO1; 
RUN;

DATA MADES_A;
	MERGE &twomoUNbooked(IN = x) VW_L(IN = y);
	BY SSNO1;
	IF x = 1;
RUN;

DATA MADES_A;
	SET MADES_A;
	IF ENTDATE_SAS >= APPDATE_SAS - 1 AND 
					  ENTDATE_SAS <= APPDATE_SAS + 60 
		THEN BOOKED = 1;
	ELSE BOOKED = 0;
	IF BOOKED = 0 THEN BRACCTNO = "";
	IF OWNBR = "" THEN OWNBR = DWOWNBR;
RUN;

DATA MADES_A;
	SET MADES_A &twomobooked;
RUN;

PROC SORT 
	DATA = MADES_A; 
	BY BRACCTNO LOANTYPE; 
RUN;

DATA UNBOOKED BOOKED;
	SET MADES_A;
	IF BRACCTNO = "" THEN OUTPUT UNBOOKED;
	ELSE OUTPUT BOOKED;
RUN;

DATA x y;
	SET BOOKED;
	BY BRACCTNO;
	IF FIRST.BRACCTNO & LAST.BRACCTNO THEN OUTPUT x;
	ELSE OUTPUT y;
RUN;

DATA y2;
	SET y;
	IF LOANTYPE = "Prequalify" THEN BRACCTNO = "";
	IF LOANTYPE = "Prequalify" THEN BOOKED = 0;
RUN;

DATA MADES_D;
	SET UNBOOKED x y2;
RUN;

DATA FINAL;
	SET MADES_D;

	IF BOOKED = 0 THEN DO;
		NETLOANAMOUNT = .;
		ENTDATE_SAS = .;
		TOTALLOANCOST = .;
		BRACCTNO = "";
		ENTYRMONTH = .;
	END;

	IF BOOKED = 1 THEN DO;
		TOTALLOANCOST = 80;
		BOOKED_MONTH = MONTH(ENTDATE_SAS);
	END;

	APPMONTH = MONTH(APPDATE_SAS);
	TOTALAPPS = 1;
	IF AMTREQUESTED < 5000 THEN COSTPERAPP = 2;
	ELSE COSTPERAPP = 3;
	COSTPERLOAN = 80;
RUN;

***CHECKS -------------------------------------------------------- ***;
PROC SQL;
	SELECT ENTYRMONTH, SUM(BOOKED) 
	FROM FINAL 
	GROUP BY 1;
QUIT;

DATA &appsminues2moago;
	SET MERGEDXX;
	IF APPYRMONTH NE &twomoago;
RUN;

DATA &allappsfile;
	SET &appsminues2moago FINAL;
RUN;

*** HERE WE ARE IDENTIFYING LOANS BOOKED THIS MONTH FROM LAST      ***;
*** MONTH'S APPLICATIONS ----------------------------------------- ***;
DATA &onemobooked &onemoUNbooked;
	SET &allappsfile;
	IF APPYRMONTH = &onemoago;
	IF BOOKED = 1 THEN OUTPUT &onemobooked;
	ELSE OUTPUT &onemoUNbooked;
RUN;

PROC SORT 
	DATA = VW_L; 
	BY SSNO1; 
RUN;

PROC SORT 
	DATA = &onemoUNbooked; 
	BY SSNO1;
RUN;

DATA MADES_A;
	MERGE &onemoUNbooked(IN = x) VW_L(IN = y);
	BY SSNO1;
	IF x = 1;
RUN;

DATA MADES_A;
	SET MADES_A;
	IF ENTDATE_SAS >= APPDATE_SAS - 1 AND 
	   ENTDATE_SAS <= APPDATE_SAS + 60 THEN BOOKED = 1;
	ELSE BOOKED = 0;
	IF BOOKED = 0 THEN BRACCTNO = "";
	IF OWNBR = "" THEN OWNBR = DWOWNBR;
RUN;


DATA MADES_A;
	SET MADES_A &onemobooked;
RUN;

PROC SORT
	DATA = MADES_A;
	BY BRACCTNO LOANTYPE;
RUN;

DATA UNBOOKED BOOKED;
	SET MADES_A;
	IF BRACCTNO = "" THEN OUTPUT UNBOOKED;
	ELSE OUTPUT BOOKED;
RUN;

DATA x y;
	SET BOOKED;
	BY BRACCTNO;
	IF FIRST.BRACCTNO & LAST.BRACCTNO THEN OUTPUT x;
	ELSE OUTPUT y;
RUN;

DATA y2;
	SET y;
	IF LOANTYPE = "Prequalify" THEN BRACCTNO = "";
	IF LOANTYPE = "Prequalify" THEN BOOKED = 0;
RUN;

DATA MADES_D;
	SET UNBOOKED x y2;
RUN;

DATA FINAL;
	SET MADES_D;

	IF BOOKED = 0 THEN DO;
		NETLOANAMOUNT = .;
		ENTDATE_SAS = .;
		TOTALLOANCOST = .;
		BRACCTNO = "";
	END;

	IF BOOKED = 1 THEN DO;
		TOTALLOANCOST = 80;
		BOOKED_MONTH = MONTH(ENTDATE_SAS);
	END;

	APPMONTH = MONTH(APPDATE_SAS);
	TOTALAPPS = 1;
	IF AMTREQUESTED < 5000 THEN COSTPERAPP = 2;
	ELSE COSTPERAPP = 3;
	COSTPERLOAN = 80;
RUN;

DATA &appsminues1moago;
	SET &allappsfile;
	IF APPYRMONTH NE &onemoago;
RUN;

DATA &allappsfile2;
	SET &appsminues1moago FINAL;
RUN;