PROC SQL;
   CREATE TABLE WORK.REPORTS_TABLE AS 
   SELECT *
      FROM WORK.ALL_APPS_3 t1;
QUIT;

DATA REPORTS_TABLE;
	SET REPORTS_TABLE;
	IF SOURCE = "LendingTree" THEN 
		TOTALAPPCOST = TOTALAPPS * COSTPERAPP;
RUN;

PROC SQL;
   CREATE TABLE WORK.OWNER_TYPE AS 
   SELECT t1.'Application Number'n AS APPNUMBER, 
          t1.'Applicant Address Ownership'n, 
          t1.'Loan Request Purpose'n
      FROM WORK.AIP_INPUT t1
      ORDER BY t1.'Application Number'n;
QUIT;

PROC SQL;
	CREATE TABLE WORK.REPORTS_TABLE_2 AS 
	SELECT t1.*, t2.APPNUMBER, t2.'Applicant Address Ownership'n, 
		   t2.'Loan Request Purpose'n
	FROM WORK.REPORTS_TABLE t1 
		LEFT JOIN WORK.OWNER_TYPE t2 ON t1.APPNUMBER=t2.APPNUMBER;
QUIT;

PROC SQL;
	CREATE TABLE WORK.REPORTS_TABLE_3 AS 
	SELECT t1.*, t2.old_bracctno, t2.old_AmtPaidLast, t2.renew_bracctno
	FROM WORK.REPORTS_TABLE_2 t1 
		LEFT JOIN WORK.ALL_APP9 t2 ON t1.BrAcctNo=t2.renew_bracctno;
QUIT;

DATA REPORTS_TABLE;
	SET REPORTS_TABLE_3;
	renew_amt = SUM(NetLoanAmount, 0) - SUM(old_AmtPaidLast, 0);
	IF RENEW_AMT NE 0 THEN RENEW_FLAG = 1;
	ELSE RENEW_FLAG = 0;
	IF RENEW_FLAG NE 1 THEN NEW_AMT = SUM(NetLoanAmount, 0);

	IF APPYRMONTH = 201804 THEN DO;
		TOTALAPPS_CURRENT = TOTALAPPS;
		PREAPPROV_CURRENT = PREAPPROVED_FLAG;
		TOTALAPPCOST_CURRENT = TOTALAPPCOST;
	END;

	IF ENTYRMONTH = 201804 THEN DO;
		BOOKED_CURRENT = BOOKED;
		NETLOANAMT_CURRENT = NetLoanAmount;
		TOTALLOANCOST_CURRENT = TOTALLOANCOST;
		RENEW_AMT_CURRENT = renew_amt;
		RENEW_FLAG_CURRENT = RENEW_FLAG;
		NEW_AMT_CURRENT = NEW_AMT;
		OLD_AMTPAIDLAST_CURRENT = OLD_AMTPAIDLAST;
	END;
RUN;
